site_name: é™†å›½æ¾çš„ç¼–ç¨‹ç¬”è®°
site_url: https://www.luguosong.com
repo_url: https://github.com/luguosong/programming-notes # å³ä¸Šè§’ä»“åº“é“¾æ¥åœ°å€
repo_name: programming-notes # å³ä¸Šè§’ä»“åº“åç§°
edit_uri: edit/main/code/
docs_dir: code

theme:
  name: material
  language: zh
  custom_dir: overrides # è‡ªå®šä¹‰ä¸»é¢˜ç›®å½•
  font:
    code: Source Code Pro
  logo: https://gcore.jsdelivr.net/gh/luguosong/programming-notes@main/code/assert/logo.gif
  favicon: https://gcore.jsdelivr.net/gh/luguosong/programming-notes@main/code/assert/logo.gif
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs #å¯¼èˆªé€‰é¡¹å¡
    - navigation.instant
    - navigation.instant.progress #å¯¼èˆªè¿›åº¦
    - navigation.tracking #URLä¼šè‡ªåŠ¨æ›´æ–°ä¸ºç›®å½•ä¸­çªå‡ºæ˜¾ç¤ºçš„æ´»åŠ¨é”šç‚¹
    - navigation.path #å¯¼èˆªè·¯å¾„
    - navigation.top #è¿”å›é¡¶éƒ¨åŠŸèƒ½
    - navigation.indexes #ç´¢å¼•é¡µé¢
    #- navigation.prune #åªæœ‰å¯è§çš„å¯¼èˆªé¡¹åŒ…å«åœ¨æ¸²æŸ“çš„HTMLä¸­
    #- header.autohide #è‡ªåŠ¨éšè—æ ‡é¢˜æ 
    - navigation.footer #åº•éƒ¨å¯¼èˆª
    - toc.follow #ç›®å½•è·Ÿéš
    - search.suggest #æœç´¢å»ºè®®
    - search.highlight #æœç´¢ç»“æœé«˜äº®
    - search.share #æœç´¢ç»“æœé¡µé¢åˆ†äº«
    - content.action.edit # ä»£ç æŸ¥çœ‹æŒ‰é’®
    - content.action.view # ä»£ç ä¿®æ”¹æŒ‰é’®
    - content.code.copy # ä»£ç å—å¤åˆ¶æŒ‰é’®
    - content.code.annotate
  palette:
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: åˆ‡æ¢åˆ°æµ…è‰²æ¨¡å¼
    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: åˆ‡æ¢åˆ°é»‘æš—æ¨¡å¼

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - tables # è¡¨æ ¼æ”¯æŒ
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true #æ§åˆ¶æ˜¯åœ¨æ„å»ºæ—¶ä½¿ç”¨Pygmentsè¿›è¡Œé«˜äº®è¿˜æ˜¯åœ¨æµè§ˆå™¨ä¸­ä½¿ç”¨JavaScriptè¯­æ³•é«˜äº®å™¨è¿›è¡Œé«˜äº®ã€‚
      anchor_linenums: true
      auto_title: true #è‡ªåŠ¨ä¸ºæ‰€æœ‰ä»£ç å—æ·»åŠ ä¸€ä¸ªæ ‡é¢˜
      line_spans: __span
      pygments_lang_class: true #æŒ‡ç¤ºPygmentsæ·»åŠ ä¸€ä¸ªCSSç±»æ¥æ ‡è¯†ä»£ç å—çš„è¯­è¨€
      linenums: true #ä¸ºæ‰€æœ‰ä»£ç å—æ·»åŠ è¡Œå·
      linenums_style: pymdownx-inline # è¡Œå·æ ·å¼
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: "#" #åœ¨æ ‡é¢˜æœ«å°¾ç”Ÿæˆæ°¸ä¹…é“¾æ¥
      separator: "_" #å°†æ ‡é¢˜idä¸­çš„ç©ºæ ¼æ›¿æ¢æˆ'_'
  - pymdownx.tabbed:
      alternate_style: true

extra:
  analytics:
    provider: google
    property: G-MT4W7HGBVZ
    feedback:
      title: æ­¤é¡µé¢æ˜¯å¦æœ‰å¸®åŠ©ï¼Ÿ
      ratings:
        - icon: material/emoticon-happy-outline
          name: æ­¤é¡µé¢å¾ˆæœ‰å¸®åŠ©
          data: 1
          note: >-
            æ„Ÿè°¢æ‚¨çš„åé¦ˆ!
        - icon: material/emoticon-sad-outline
          name: æ­¤é¡µå¯ä»¥æ”¹è¿›
          data: 0
          note: >-
            æ„Ÿè°¢æ‚¨çš„åé¦ˆï¼è¯·ä½¿ç”¨æˆ‘ä»¬çš„
            <a href="https://github.com/luguosong/programming-notes/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">åé¦ˆè¡¨</a>
            å¸®åŠ©æˆ‘ä»¬æ”¹è¿›æ­¤é¡µé¢ã€‚
  generator: true # æ˜¾ç¤ºä½¿ç”¨Material for MkDocsåˆ¶ä½œ
  social: #åº•éƒ¨ç¤¾äº¤åª’ä½“é“¾æ¥
    - icon: fontawesome/brands/github
      link: https://github.com/luguosong
      name: Github
    - icon: simple/wechat
      link: https://gcore.jsdelivr.net/gh/luguosong/images@master/blog-img/202404272008366.png
      name: å¾®ä¿¡

plugins:
  - statistics: # å­—æ•°ç»Ÿè®¡æ’ä»¶ï¼šhttps://github.com/TonyCrane/mkdocs-statistics-plugin
      words_per_minute: 50
      codelines_per_minute: 30
  - glightbox: # å›¾ç‰‡æŸ¥çœ‹æ’ä»¶
      touchNavigation: true
      loop: false
      zoomable: true
      draggable: false
      auto_caption: true
      background: #000000
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true

extra_css:
  - custom/css/font.css
  - custom/css/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - custom/js/custom.js
  - custom/js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

exclude_docs: |
  **/node_modules

copyright: Copyright &copy; 2024 Lu Guosong #ç‰ˆæƒä¿¡æ¯

nav:
  - ä¸»é¡µ: index.md
  - åŸºç¡€çŸ¥è¯†:
      - basic/index.md
      - è®¡ç®—æœºç»„æˆåŸç†: basic/computer_architecture_principles/index.md
      - æ“ä½œç³»ç»Ÿ:
          - basic/operating_system/index.md
      - è®¡ç®—æœºç½‘ç»œ:
          - basic/computer_network/index.md
          - åº”ç”¨å±‚-HTTP: basic/computer_network/application_http/index.md
      - æ•°æ®ç»“æ„ä¸ç®—æ³•åˆ†æ:
          - basic/data_structures_and_algorithm_analysis/index.md
          - åŸºç¡€:
              - basic/data_structures_and_algorithm_analysis/01_foundations/index.md
              - ç®—æ³•åœ¨è®¡ç®—ä¸­çš„ä½œç”¨: basic/data_structures_and_algorithm_analysis/01_foundations/01_the_role_of_algorithms_in_computers/index.md
  - å‰ç«¯:
      - front_end/index.md
      - HTML:
          - front_end/html/index.md
          - åŸºç¡€: front_end/html/basic/index.md
          - HTML5: front_end/html/html5/index.md
      - CSS:
          - front_end/css/index.md
      - JavaScript:
          - front_end/js/index.md
          - JavaScriptç®€ä»‹: front_end/js/01_Introduction_to_JavaScript/index.md
          - è¯æ³•ç»“æ„: front_end/js/02_Lexical_Structure/index.md
          - ç±»å‹ã€å€¼å’Œå˜é‡: front_end/js/03_Types_Values_and_Variables/index.md
          - è¡¨è¾¾å¼ä¸æ“ä½œç¬¦: front_end/js/04_Expressions_and_Operators/index.md
          - è¯­å¥: front_end/js/05_Statements/index.md
          - å¯¹è±¡: front_end/js/06_Objects/index.md
          - æ•°ç»„: front_end/js/07_Arrays/index.md
          - å¼‚æ­¥ç¼–ç¨‹: front_end/js/13_Asynchronous_JavaScript/index.md
      - TypeScript:
          - front_end/typescript/index.md
          - åŸºæœ¬è¯­æ³•: front_end/typescript/basic/index.md
          - å·¥ç¨‹åŒ–: front_end/typescript/engineering/index.md
      - ä»£ç æ‰“åŒ…:
          - front_end/code_bundler/index.md
          - webpack: front_end/code_bundler/webpack/index.md
      - Vue:
          - front_end/vue/index.md
      - React:
          - front_end/react/index.md
          - åŸºæœ¬è¯­æ³•: front_end/react/basic/index.md
          - React Router: front_end/react/react_router/index.md
          - Next.js: front_end/react/nextjs/index.md
  - JavaåŸºç¡€:
      - java/index.md
      - JavaSE:
          - java/javase/src/main/java/com/luguosong/index.md
          - æ¦‚è¿°: java/javase/src/main/java/com/luguosong/_01_overview/index.md
          - è¯­è¨€åŸºç¡€: java/javase/src/main/java/com/luguosong/_02_basic/index.md
          - é¢å‘å¯¹è±¡: java/javase/src/main/java/com/luguosong/_03_object_oriented/index.md
      - Javaæ—¥å¿—:
          - java/log/index.md
          - åŸºç¡€: java/log/basic/index.md
  - æœåŠ¡ç«¯å¼€å‘:
      - java_serve/index.md
      - Springæ¡†æ¶:
          - java_serve/spring/index.md
          - Springæ¡†æ¶ç‰ˆæœ¬è¯´æ˜: java_serve/spring/spring-framework-versions/index.md
          - æ§åˆ¶åè½¬: java_serve/spring/basic/index.md
          - é¢å‘åˆ‡é¢ç¼–ç¨‹: java_serve/spring/aop/index.md
          - SSMæ•´åˆ: java_serve/spring/ssm/index.md
      - Webåº”ç”¨:
          - java_serve/web_application/index.md
          - TomcatæœåŠ¡å™¨: java_serve/web_application/tomcat/index.md
          - Servlet: java_serve/web_application/servlet/index.md
          - JSP: java_serve/web_application/jsp/index.md
          - Sessionå’ŒCookie: java_serve/web_application/session_cookie/index.md
          - è¿‡æ»¤å™¨å’Œç›‘å¬å™¨: java_serve/web_application/filter_listener/index.md
          - MVCæ¶æ„æ¨¡å¼: java_serve/web_application/mvc/index.md
          - å“åº”å¼ç¼–ç¨‹: java_serve/web_application/reactive/index.md
      - æ•°æ®åº“å¼€å‘:
          - java_serve/database/index.md
          - JDBC: java_serve/database/jdbc/index.md
          - Mybatis: java_serve/database/mybatis/index.md
          - Mybatis Plus: java_serve/database/mybatis_plus/index.md
      - è®¤è¯å’Œé‰´æƒ:
          - java_serve/authentication/index.md
          - Spring Securityå®æˆ˜:
              - java_serve/authentication/spring-security/index.md
              - å®‰å…¨ç°çŠ¶: java_serve/authentication/spring-security/01-security-today/index.md
              - Spring Securityå…¥é—¨: java_serve/authentication/spring-security/02_hello/index.md
              - ç®¡ç†ç”¨æˆ·: java_serve/authentication/spring-security/03_managing_users/index.md
              - ç®¡ç†å¯†ç : java_serve/authentication/spring-security/04_managing_passwords/index.md
              - ç½‘ç»œåº”ç”¨çš„å®‰å…¨æ€§å§‹äºè¿‡æ»¤å™¨: java_serve/authentication/spring-security/05_begins_with_filters/index.md
              - å®ç°èº«ä»½è®¤è¯: java_serve/authentication/spring-security/06_implementing_authentications/index.md
      - Spring Boot:
          - java_serve/springboot/index.md
          - åŸºç¡€çŸ¥è¯†: java_serve/springboot/basic/index.md
      - åˆ†å¸ƒå¼/å¾®æœåŠ¡:
          - java_serve/distributed/index.md
          - ç½‘å…³:
              - java_serve/distributed/gateway/index.md
              - Spring Cloud Gateway: java_serve/distributed/gateway/spring_cloud_gateway/index.md
  - ä¸“é¡¹ç ”ç©¶:
      - topics/index.md
      - è®¾è®¡æ¨¡å¼:
          - topics/design_pattern/src/main/java/com/luguosong/index.md
          - æ¦‚è¿°: topics/design_pattern/src/main/java/com/luguosong/overview/index.md
          - åˆ›å»ºå‹æ¨¡å¼:
              - topics/design_pattern/src/main/java/com/luguosong/creational/index.md
          - ç»“æ„å‹æ¨¡å¼:
              - topics/design_pattern/src/main/java/com/luguosong/structural/index.md
              - ä»£ç†ğŸ”¥: topics/design_pattern/src/main/java/com/luguosong/structural/proxy/index.md
          - è¡Œä¸ºå‹æ¨¡å¼:
              - topics/design_pattern/src/main/java/com/luguosong/behavioral/index.md
              - è´£ä»»é“¾: topics/design_pattern/src/main/java/com/luguosong/behavioral/chain_of_responsibility/index.md
      - Maven:
          - topics/maven/index.md
          - MavenåŸºç¡€æ•™ç¨‹: topics/maven/base/index.md
      - sql:
          - topics/sql/index.md
          - ç¯å¢ƒæ­å»º: topics/sql/environment_building.md
          - æ•°æ®åº“å®šä¹‰è¯­è¨€: topics/sql/ddl.md
          - æ•°æ®åº“æ“ä½œè¯­è¨€: topics/sql/dml.md
          - æ•°æ®åº“æ§åˆ¶è¯­è¨€: topics/sql/dcl.md
      - Git:
          - topics/git/index.md
      - Linux:
          - topics/linux/index.md
          - Linuxæ¦‚è¿°: topics/linux/basic/index.md
          - æ–‡ä»¶ç³»ç»Ÿ: topics/linux/file_directory/index.md
          - shellè„šæœ¬: topics/linux/shell/index.md
          - ä½¿ç”¨è€…ç®¡ç†: topics/linux/user_management/index.md
          - ç³»ç»Ÿç®¡ç†å‘˜: topics/linux/system_administrator/index.md
      - å¯†ç å­¦:
          - topics/cryptography/src/main/java/com/luguosong/index.md
      - iTextåº“-PDFç­¾ç« :
          - topics/itext-signatures/src/main/java/com/luguosong/index.md
          - ç†è§£æ•°å­—ç­¾åçš„æ¦‚å¿µ: topics/itext-signatures/src/main/java/com/luguosong/chapter01_understanding_the_concept_of_digital_signatures/index.md
          - PDFå’Œæ•°å­—ç­¾å: topics/itext-signatures/src/main/java/com/luguosong/chapter02_pdf_and_digital_signatures/index.md
          - è¯ä¹¦é¢å‘æœºæ„ã€è¯ä¹¦åŠé”€å’Œæ—¶é—´æˆ³: topics/itext-signatures/src/main/java/com/luguosong/chapter03_certificate_authorities_certificate_revocation_and_time_stamping/index.md
          - å¤–éƒ¨åˆ›å»ºç­¾å: topics/itext-signatures/src/main/java/com/luguosong/chapter04_creating_signatures_externally/index.md
          - ç­¾åæ–‡æ¡£çš„éªŒè¯: topics/itext-signatures/src/main/java/com/luguosong/chapter05_validation_of_signed_documents/index.md
      - å¸¸ç”¨å·¥å…·:
          - topics/tools/index.md
          - å†…ç½‘ç©¿é€-frp: topics/tools/frp/index.md
  - è‹±è¯­:
      - english/index.md
      - éŸ³æ ‡: english/phonetic_symbol/index.md
      - æ–°æ¦‚å¿µå•è¯: english/new_concept_english/index.md
      - è¯­æ³•: english/grammar/index.md
  - æ•°å­¦:
      - math/index.md
      - Latexå…¬å¼å¯¹ç…§è¡¨: math/latex/index.md
      - æ•°å­¦åŸºç¡€: math/basic/index.md
  - å…¶å®ƒ:
      - other/index.md
      - IDEAä½¿ç”¨å¿ƒå¾—: other/idea/index.md
      - ç½‘ç«™æ­å»º:
          - other/website_building/index.md
          - ç½‘ç«™é…ç½®: other/website_building/website_building.md
          - markdownç¤ºä¾‹: other/website_building/demo.md
      - Windowå‘½ä»¤ç¬”è®°: other/windows_cmd/index.md
      - MathJax:
          - other/mathjax/index.md
          - å…¬å¼ä»£ç ç¤ºä¾‹: other/mathjax/formulas/index.md
      - å†å²:
          - other/history/index.md
          - ä¸­å›½å²: other/history/chinese_history/index.md


